In [1]:
import pandas as pd

In [28]:
dataset = pd.read_csv(r'C:\\Users\\Aliasger B\\1001_ai\\1001_ai_python\\Ai\\LearningMachineLearning\\datasets\\iris_folwer.csv')

dataset

      id  Sepal_length  Sepal_width  Petal_length  Petal_width      Species
0      1           5.1          3.5           1.4          0.2     i_setosa
1      2           4.9          3.0           1.4          0.2     i_setosa
2      3           4.7          3.2           1.3          0.2     i_setosa
3      4           4.6          3.1           1.5          0.2     i_setosa
4      5           5.0          3.6           1.4          0.3     i_setosa
..   ...           ...          ...           ...          ...          ...
145  146           6.7          3.0           5.2          2.3  i_virginica
146  147           6.3          2.5           5.0          1.9  i_virginica
147  148           6.5          3.0           5.2          2.0  i_virginica
148  149           6.2          3.4           5.4          2.3  i_virginica
149  150           5.9          3.0           5.1          1.8  i_virginica

[150 rows x 6 columns]

In [29]:
x = dataset.iloc[:, 1:5]

In [30]:
x

     Sepal_length  Sepal_width  Petal_length  Petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.3
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [31]:
y = dataset.iloc[:, -1]

In [32]:
y

0         i_setosa
1         i_setosa
2         i_setosa
3         i_setosa
4         i_setosa
          ...
145    i_virginica
146    i_virginica
147    i_virginica
148    i_virginica
149    i_virginica
Name: Species, Length: 150, dtype: object

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [34]:
x_train

     Sepal_length  Sepal_width  Petal_length  Petal_width
20            5.4          3.4           1.7          0.2
48            5.3          3.7           1.5          0.2
14            5.8          4.0           1.2          0.2
82            5.8          2.7           3.9          1.2
74            6.4          2.9           4.3          1.3
..            ...          ...           ...          ...
118           7.7          2.6           6.9          2.3
138           6.0          3.0           4.8          1.8
89            5.5          2.5           4.0          1.3
36            5.5          3.5           1.3          0.2
34            4.9          3.1           1.5          0.2

[120 rows x 4 columns]

In [35]:
x_test

     Sepal_length  Sepal_width  Petal_length  Petal_width
96            5.7          2.9           4.2          1.3
81            5.5          2.4           3.7          1.0
11            4.8          3.4           1.6          0.2
126           6.2          2.8           4.8          1.8
45            4.8          3.0           1.4          0.3
107           7.3          2.9           6.3          1.8
83            6.0          2.7           5.1          1.6
84            5.4          3.0           4.5          1.5
117           7.7          3.8           6.7          2.2
136           6.3          3.4           5.6          2.4
8             4.4          2.9           1.4          0.2
46            5.1          3.8           1.6          0.2
86            6.7          3.1           4.7          1.5
44            5.1          3.8           1.9          0.4
85            6.0          3.4           4.5          1.6
147           6.5          3.0           5.2          2.0
87            6.3          2.3           4.4          1.3
77            6.7          3.0           5.0          1.7
25            5.0          3.0           1.6          0.2
75            6.6          3.0           4.4          1.4
12            4.8          3.0           1.4          0.1
137           6.4          3.1           5.5          1.8
133           6.3          2.8           5.1          1.5
148           6.2          3.4           5.4          2.3
51            6.4          3.2           4.5          1.5
3             4.6          3.1           1.5          0.2
141           6.9          3.1           5.1          2.3
62            6.0          2.2           4.0          1.0
112           6.8          3.0           5.5          2.1
102           7.1          3.0           5.9          2.1

In [36]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')

svc.fit(x_train, y_train)

SVC(kernel='linear')

In [37]:
svc.predict(x_test)

array(['i_versicolor', 'i_versicolor', 'i_setosa', 'i_virginica',
       'i_setosa', 'i_virginica', 'i_virginica', 'i_versicolor',
       'i_virginica', 'i_virginica', 'i_setosa', 'i_setosa',
       'i_versicolor', 'i_setosa', 'i_versicolor', 'i_virginica',
       'i_versicolor', 'i_versicolor', 'i_setosa', 'i_versicolor',
       'i_setosa', 'i_virginica', 'i_virginica', 'i_virginica',
       'i_versicolor', 'i_setosa', 'i_virginica', 'i_versicolor',
       'i_virginica', 'i_virginica'], dtype=object)

In [38]:
svc.score(x_test, y_test)

0.9666666666666667